import java.util.*;

class ComplexDemo{
	public static void main(String[] args){
		System.out.println("1. Complex of TYPE INT");
		Complex c1 = new Complex(2,3);
		Complex c2 = new Complex(4,7);
		//System.out.println(c1);
		Complex sum1 = c1.addition(c2);
		Complex diff1 = c1.subtraction(c2);
		double abs1 = c1.absolute();
		double abs2 = c2.absolute();
		Complex mul1 = c1.multiply(c2);
		Complex con1 = c1.getConjugate();
		Complex con2 = c2.getConjugate();
		System.out.println("Sum of 2+3i and 4+7i: " + sum1);
		System.out.println("Difference of 2+3i and 4+7i: " + diff1);
		System.out.println("Absolute of 2+3i: " + abs1);
		System.out.println("Absolute of 4+7i: " + abs2);
		System.out.println("Multiplication of 2+3i and 4+7i: " + mul1);
		System.out.println("Conjugate of 2+3i: " + con1);
		System.out.println("Conjugate of 4+7i: " + con2);
		System.out.println();

		System.out.println("2. Use of arbitary types without generics");
		System.out.println("\t a. INT TYPE:");
		Complex_arb c3 = new Complex_arb(2,3);
		Complex_arb c4 = new Complex_arb(4,7);
		Complex_arb sum2 = c3.addition(c4);
		Complex_arb diff2 = c3.subtraction(c4);
		double abs3 = c3.absolute();
		double abs4 = c4.absolute();
		Complex_arb mul2 = c3.multiply(c4);
		Complex_arb con3 = c3.getConjugate();
		Complex_arb con4 = c4.getConjugate();
		System.out.println("\t Sum of 2+3i and 4+7i: " + sum2);
		System.out.println("\t Difference of 2+3i and 4+7i: " + diff2);
		System.out.println("\t Absolute of 2+3i: " + abs3);
		System.out.println("\t Absolute of 4+7i: " + abs4);
		System.out.println("\t Multiplication of 2+3i and 4+7i: " + mul2);
		System.out.println("\t Conjugate of 2+3i: " + con3);
		System.out.println("\t Conjugate of 4+7i: " + con4);
		System.out.println();

		System.out.println("\t b. FLOAT TYPE:");
		Complex_arb c5 = new Complex_arb(2.5f,3.2f);
		Complex_arb c6 = new Complex_arb(4.6f,7.78f);
		Complex_arb sum3 = c5.addition(c6);
		Complex_arb diff3 = c5.subtraction(c6);
		double abs5 = c5.absolute();
		double abs6 = c6.absolute();
		Complex_arb mul3 = c5.multiply(c6);
		Complex_arb con5 = c5.getConjugate();
		Complex_arb con6 = c6.getConjugate();
		System.out.println("\t Sum of 2.5+3.2i and 4.6+7.78i: " + sum3);
		System.out.println("\t Difference of 2.5+3.2i and 4.6+7.78i: " + diff3);
		System.out.println("\t Absolute of 2.5+3.2i: " + abs5);
		System.out.println("\t Absolute of 4.6+7.78i: " + abs6);
		System.out.println("\t Multiplication of 2.5+3.2i and 4.6+7.78i: " + mul3);
		System.out.println("\t Conjugate of 2.5+3.2i: " + con5);
		System.out.println("\t Conjugate of 4.6+7.78i: " + con6);
		System.out.println();

		System.out.println("\t c. DOUBLE TYPE:");
		Complex_arb c7 = new Complex_arb(2.536,3.245);
		Complex_arb c8 = new Complex_arb(4.645,7.785);
		Complex_arb sum4 = c7.addition(c8);
		Complex_arb diff4 = c7.subtraction(c8);
		double abs7 = c7.absolute();
		double abs8 = c8.absolute();
		Complex_arb mul4 = c7.multiply(c8);
		Complex_arb con7 = c7.getConjugate();
		Complex_arb con8 = c8.getConjugate();
		System.out.println("\t Sum of 2.536+3.245i and 4.645+7.785i: " + sum4);
		System.out.println("\t Difference of 2.536+3.245i and 4.645+7.785i: " + diff4);
		System.out.println("\t Absolute of 2.536+3.245i: " + abs7);
		System.out.println("\t Absolute of 4.645+7.785i: " + abs8);
		System.out.println("\t Multiplication of 2.536+3.245i and 4.645+7.785i: " + mul4);
		System.out.println("\t Conjugate of 2.536+3.245i: " + con7);
		System.out.println("\t Conjugate of 4.645+7.785i: " + con8);
		System.out.println();

		System.out.println("3. With generics");
		System.out.println("\t c. INT TYPE:");
		Complex_gen g3 = new Complex_gen(2,3);
		Complex_gen g4 = new Complex_gen(4,7);
		Complex_gen sum5 = g3.addition(g4);
		Complex_gen diff5 = g3.subtraction(g4);
		double abs_1 = g3.absolute();
		double abs_2= g4.absolute();
		Complex_gen mul5 = g3.multiply(g4);
		Complex_gen con_1 = g3.getConjugate();
		Complex_gen con_2= g4.getConjugate();
		System.out.println("\t Sum of 2+3i and 4+7i: " + sum5);
		System.out.println("\t Difference of 2+3i and 4+7i: " + diff5);
		System.out.println("\t Absolute of 2+3i: " + abs_1);
		System.out.println("\t Absolute of 4+7i: " + abs_2);
		System.out.println("\t Multiplication of 2+3i and 4+7i: " + mul5);
		System.out.println("\t Conjugate of 2+3i: " + con_1);
		System.out.println("\t Conjugate of 4+7i: " + con_2);
		System.out.println();

		System.out.println("\t b. FLOAT TYPE:");
		Complex_gen g5 = new Complex_gen(2.5f,3.2f);
		Complex_gen g6 = new Complex_gen(4.6f,7.78f);
		Complex_gen sum6 = g5.addition(g6);
		Complex_gen diff6 = g5.subtraction(g6);
		double abs_3 = g5.absolute();
		double abs_4= g6.absolute();
		Complex_gen mul6 = g5.multiply(g6);
		Complex_gen con_3 = g5.getConjugate();
		Complex_gen con_4 = g6.getConjugate();
		System.out.println("\t Sum of 2.5+3.2i and 4.6+7.78i: " + sum6);
		System.out.println("\t Difference of 2.5+3.2i and 4.6+7.78i: " + diff6);
		System.out.println("\t Absolute of 2.5+3.2i: " + abs_3);
		System.out.println("\t Absolute of 4.6+7.78i: " + abs_4);
		System.out.println("\t Multiplication of 2.5+3.2i and 4.6+7.78i: " + mul6);
		System.out.println("\t Conjugate of 2.5+3.2i: " + con_3);
		System.out.println("\t Conjugate of 4.6+7.78i: " + con_4);
		System.out.println();

		System.out.println("\t c. DOUBLE TYPE:");
		Complex_gen g7 = new Complex_gen(2.536,3.245);
		Complex_gen g8 = new Complex_gen(4.645,7.785);
		Complex_gen sum7 = g7.addition(g8);
		Complex_gen diff7 = g7.subtraction(g8);
		double abs_5 = g7.absolute();
		double abs_6 = g8.absolute();
		Complex_gen mul7 = g7.multiply(g8);
		Complex_gen con_5 = g7.getConjugate();
		Complex_gen con_6 = g8.getConjugate();
		System.out.println("\t Sum of 2.536+3.245i and 4.645+7.785i: " + sum7);
		System.out.println("\t Difference of 2.536+3.245i and 4.645+7.785i: " + diff7);
		System.out.println("\t Absolute of 2.536+3.245i: " + abs_5);
		System.out.println("\t Absolute of 4.645+7.785i: " + abs_6);
		System.out.println("\t Multiplication of 2.536+3.245i and 4.645+7.785i: " + mul7);
		System.out.println("\t Conjugate of 2.536+3.245i: " + con_5);
		System.out.println("\t Conjugate of 4.645+7.785i: " + con_6);
		System.out.println();

	}
}
